name: My App Deployment
on: [push]
jobs:
  Build-My-App:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Run ESLint
        run: npm run lint:ci

      - name: Run Tests
        run: npm run test:ci

      - name: Run Build
        run: npm run build

      - name: Run Lighthouse CI
        run: npm run lighthouse:ci
